apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  serviceAccountName: myjenkins
  securityContext:
    runAsUser: 0
  containers:
    - name: jnlp
      image: jenkins/jnlp-agent-maven
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"
    - name: docker
      image: docker
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "500m"
