apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  serviceAccountName: myjenkins
  containers:
    - name: docker
      image: docker
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
