apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  volumes:
    - name: dind-storage
      emptyDir: {}
  serviceAccountName: myjenkins
  securityContext:
    runAsUser: 0
  containers:
    # - name: jnlp
    #   image: mirantis/jnlp-slave
    #   resources:
    #     requests:
    #       memory: "128Mi"
    #       cpu: "500m"
    #     limits:
    #       memory: "1000Mi"
    #       cpu: "500m"
    - name: docker
      image: docker:dind
      securityContext:
        runAsUser: 0
        privileged: true
        allowPrivilegeEscalation: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
